### PR TITLE
WIP Restructure tomesh.101 for future outreach materials development

### PR DESCRIPTION
**Pull request by dcwalk**
Still working on this, have just done the preliminary move, remaining:
- [X] Update readme to reflect structure
- [X] Propose best way to use gh-pages going forward
- [X] Investigate whether modularizing presentations makes sense now

This could partially address #1, edit: after review this will be handles separately as that is more about content, rather than structure/folder hierarchy.

### CODE REVIEW

**Comment by dcwalk** [comment]
An update on this: I think that we should consider having the gh-pages act as a standalone page for all of the tomesh.101 material as it gets created.

For now I've opened an issue (#7) to remove the gh-pages as it stands.

**Comment by benhylau** [comment]
Have we decide on how to render the material? And does it get hosted on **gh-pages** as a blog or website server?

**Comment by dcwalk** [comment]
Our discussion wasn't firm on exactly where material would be hosted. I think for the tutorial, reference spec, and intro materials the goal was to have them on the website. 

Content for a more 'internal' audience (aka other mesh groups) was left undecided, and having a prettier way to navigate all the presentations linked from a **gh-page** for use might make sense?

**Comment by dcwalk** [comment]
Okay, I think this is done and we have a good first pass for the readme! Comments please. Will merge in a couple days barring any.

**Pull request merged**
